apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ruinuo/docker-fastapi:965e2a9147e8a3b4f5e91cd792265ce42bd777e0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"       # 最低需求 0.1 核
            limits:
              cpu: "500m"       # 上限 0.5 核
